name = "lullaby"
main = "src/index.js"
compatibility_date = "2025-07-18"

routes = [
  { pattern = "lullaby.aistuffforparents.com", custom_domain = true },
  { pattern = "timer.aistuffforparents.com", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "storytime-library"
database_id = "2331a812-9747-4019-9f5a-b3abbf08df04"
